name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
     
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./build"

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
